import random
import json
from .Unit import Unit

#load conf file for unit IDs and sensor IDs
confFile = './conf.json'
unitData = []

with open(confFile, 'r') as data:
    unitData = json.loads(data.read())
    data.close()

#sensor_type = unitData["sensors"]["type"]
#print(sensor_type)

class SensorData(Unit):
    #radom data generated by sensors

    def __init__(self,sensor_id, sensor_type, unit_id):
        self.unit_id = unit_id
        self.sensor_id = sensor_id
        self.sensor_type = sensor_type
        self.cistern_temperature = round(random.uniform(2.5, 4), 1)
        self.ambient_temperature = round(random.uniform(8, 14), 1)
        self.cistern_milk_weight = round(random.uniform(3512, 4607), 0)
        self.finish_product_weight = round(random.uniform(0, 100), 0)
        self.pH = round(random.uniform(6.8, 7.2), 1)
        self.kplus = round(random.uniform(35, 47), 0)
        self.nacl = round(random.uniform(1, 1.7), 1)
        self.salmonella_lvl = round(random.uniform(17, 37), 0)
        self.ecoli_lvl = round(random.uniform(35, 49), 0)
        self.listeria_lvl = round(random.uniform(28, 54), 0)

    def get_sensor_id(self):
        return self.sensor_id

    def set_sensor_id(self, x):
        self.sensor_id = x

    def get_sensor_type(self):
        return self.sensor_type

    def set_sensor_type(self, x):
        self.sensor_type = x

